-- =====================================================================
-- PetHaven Group - database schema, phase 1: the three UC1 source systems
-- (Supabase / PostgreSQL). Safe to re-run (IF NOT EXISTS).
--
-- Apply with:  python scripts/apply_schema.py
--
-- SCOPE OF THIS FILE
--   Assignment 2 prototype for UC1 (Customer & Pet Profile). Only the three
--   source systems (the Bronze landing layer) are defined here, enough to
--   load the initial synthetic data. The later layers of the agreed
--   architecture are added in later pull requests:
--     Silver : stg_*  (standardised copies)  +  mdm_*  (match, merge,
--              survivorship, golden customer / pet, cross-reference)
--     Gold   : dw_*   (dimensional data warehouse, star schema)
--     Reports: rpt_*  (UC1 report views)
--
-- THE THREE SOURCES (each is its own "system" with its own keys)
--   src_pos_*       SRC_POS       in-store point of sale + loyalty members
--   src_digital_*   SRC_DIGITAL   website and mobile app (accounts, pets, orders)
--   src_grooming_*  SRC_GROOMING  grooming salon system (clients, pets, appointments)
--
-- RULES
--   * Each source keeps its OWN keys and its own copy of customers (and pets,
--     where it has them), on purpose: the systems share no identifiers. This
--     is the UC1 problem; matching them is the job of the later MDM layer.
--   * Foreign keys exist only INSIDE one source, never between sources.
--     Cross-source references (e.g. a salon or pickup store named by a
--     different system) are plain text columns.
--   * Each source captures data the way a real system of that kind would, so
--     formats differ between sources ON PURPOSE (see "UC1 data issues" under
--     each source). Do not "fix" these here; staging standardises them.
--   * Table prefixes in the public schema (not separate Postgres schemas) so
--     supabase-py reaches every table without extra API settings.
--   * Text CHECK constraints instead of enums; identity columns are
--     "BY DEFAULT" so the synthetic data generator can load its own IDs.
--   * Every table carries updated_at (or an event timestamp) because MDM
--     survivorship uses "most recently updated" as a tie-breaker.
--
-- Removing tables from an older version of this schema (src_product_*,
-- src_customer_*, src_pos_stock, mdm_*, gov_*, v_* ...):
--   python scripts/apply_schema.py --reset      (development database only)
-- =====================================================================


-- =====================================================================
-- SRC_POS  -  in-store point of sale
-- Holds: stores, loyalty members (the only customer record in POS), sales
-- and sale lines. POS has NO pet data.
-- UC1 data issues by design:
--   * Customer name is ONE free-text field typed at the till
--     ("EMMA WILSON", "L Chen"), not split into first / last name.
--   * Phone is typed in any format ("0412 345 678", "+61 430 123 456").
--   * Email is optional and often missing.
--   * The same person can sign up twice at different stores (duplicate
--     members inside POS).
-- =====================================================================
create table if not exists public.src_pos_stores (
  store_id    bigint generated by default as identity primary key,
  store_code  text not null unique,              -- e.g. 'S01'
  store_name  text not null unique,              -- e.g. 'PetHaven Parramatta'
  suburb      text,
  state       text,
  postcode    text
);

create table if not exists public.src_pos_loyalty_members (
  member_no           text primary key,          -- POS customer ID, e.g. 'P1001'
  full_name           text not null,             -- one field, as typed at the till
  phone               text,                      -- free format
  email               text,                      -- optional
  postcode            text,
  loyalty_tier        text not null default 'bronze'
                        check (loyalty_tier in ('bronze','silver','gold')),
  registered_store_id bigint references public.src_pos_stores (store_id),
  registered_at       timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists public.src_pos_sales (
  sale_id         bigint generated by default as identity primary key,
  store_id        bigint not null references public.src_pos_stores (store_id),
  member_no       text references public.src_pos_loyalty_members (member_no),  -- null = walk-in
  sold_at         timestamptz not null,
  payment_method  text not null check (payment_method in ('card','cash','eftpos','gift_card'))
);

create table if not exists public.src_pos_sale_lines (
  sale_line_id        bigint generated by default as identity primary key,
  sale_id             bigint not null references public.src_pos_sales (sale_id) on delete cascade,
  product_code        text not null,          -- POS product code (products are out of UC1 scope)
  product_description text,
  quantity            integer not null check (quantity > 0),
  unit_price          numeric(10,2) not null check (unit_price >= 0)
);


-- =====================================================================
-- SRC_DIGITAL  -  website and mobile app
-- Holds: customer accounts, pet profiles registered by the customer,
-- online orders and order lines. Names stores as text.
-- UC1 data issues by design:
--   * Customers maintain their own details, so email is required and
--     usually the most current, but it may differ from the email in
--     POS / grooming (e.g. a new email address).
--   * Mobile is often stored in international format ('+61412345678').
--   * Pets use a controlled species list (app dropdown), but breed is free
--     text, so it will not match the salon's spelling.
-- =====================================================================
create table if not exists public.src_digital_customers (
  account_id    bigint generated by default as identity primary key,  -- web customer ID, e.g. 501
  email         text not null unique,
  first_name    text,
  last_name     text,
  mobile        text,                          -- free format, often +61...
  postcode      text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.src_digital_pets (
  pet_id      bigint generated by default as identity primary key,
  account_id  bigint not null references public.src_digital_customers (account_id) on delete cascade,
  name        text not null,
  species     text not null check (species in ('dog','cat','bird','fish','small_animal','reptile','other')),
  breed       text,                            -- free text typed by the customer
  birth_date  date,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.src_digital_orders (
  order_no         text primary key,           -- e.g. 'WEB-100045'
  account_id       bigint references public.src_digital_customers (account_id),  -- null = guest checkout
  ordered_at       timestamptz not null,
  status           text not null check (status in ('placed','fulfilled','cancelled')),
  delivery_method  text not null check (delivery_method in ('delivery','click_and_collect')),
  pickup_store     text                        -- store NAME as text, only for click and collect
);

create table if not exists public.src_digital_order_lines (
  order_line_id  bigint generated by default as identity primary key,
  order_no       text not null references public.src_digital_orders (order_no) on delete cascade,
  sku            text not null,                -- web SKU (products are out of UC1 scope)
  product_name   text,
  quantity       integer not null check (quantity > 0),
  unit_price     numeric(10,2) not null check (unit_price >= 0)
);


-- =====================================================================
-- SRC_GROOMING  -  grooming salon system (a separate booking application)
-- Holds: salon clients, the pets they bring in (with care notes), the
-- service menu and appointments. Names the salon's store as text.
-- UC1 data issues by design:
--   * Client name is one field typed by salon staff in mixed formats
--     ("Wilson, Emma" or "Emma Wilson").
--   * Species and breed are free text ("Canine", "Golden Retriver").
--   * Some older / walk-in pets have NO client_code; staff only noted an
--     owner phone number in owner_phone_note. These pets cannot be linked
--     to a customer without MDM.
--   * The same client can be created twice by different salons.
-- =====================================================================
create table if not exists public.src_grooming_clients (
  client_code  text primary key,               -- salon customer ID, e.g. 'G01'
  client_name  text not null,                  -- one field, mixed formats
  contact_no   text,                           -- free format
  email        text,
  postcode     text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists public.src_grooming_pets (
  pet_code          text primary key,          -- salon pet ID, e.g. 'GP01'
  client_code       text references public.src_grooming_clients (client_code),  -- null = owner not linked
  pet_name          text not null,
  species           text,                      -- free text, e.g. 'Canine', 'dog', 'Feline'
  breed             text,                      -- free text, e.g. 'Golden Retriver', 'Staffy'
  birth_date        date,
  care_notes        text,                      -- allergies, behaviour, handling notes
  owner_phone_note  text,                      -- phone written down when no client record exists
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create table if not exists public.src_grooming_services (
  service_code  text primary key,              -- e.g. 'SV01'
  service_name  text not null unique,          -- e.g. 'Full Groom'
  base_price    numeric(10,2) not null check (base_price >= 0),
  duration_min  integer not null check (duration_min > 0)
);

create table if not exists public.src_grooming_appointments (
  appointment_id  bigint generated by default as identity primary key,
  pet_code        text not null references public.src_grooming_pets (pet_code),
  service_code    text not null references public.src_grooming_services (service_code),
  salon_store     text not null,               -- store NAME as text (no key shared with POS)
  appointment_at  timestamptz not null,
  groomer_name    text,
  status          text not null check (status in ('booked','completed','cancelled','no_show')),
  price_charged   numeric(10,2) check (price_charged >= 0),   -- null until completed
  groomer_notes   text
);


-- =====================================================================
-- INDEXES on foreign-key columns (Postgres does not create these itself)
-- =====================================================================
create index if not exists idx_src_pos_loyalty_members_store   on public.src_pos_loyalty_members (registered_store_id);
create index if not exists idx_src_pos_sales_store             on public.src_pos_sales (store_id);
create index if not exists idx_src_pos_sales_member            on public.src_pos_sales (member_no);
create index if not exists idx_src_pos_sale_lines_sale         on public.src_pos_sale_lines (sale_id);
create index if not exists idx_src_digital_pets_account        on public.src_digital_pets (account_id);
create index if not exists idx_src_digital_orders_account      on public.src_digital_orders (account_id);
create index if not exists idx_src_digital_lines_order         on public.src_digital_order_lines (order_no);
create index if not exists idx_src_grooming_pets_client        on public.src_grooming_pets (client_code);
create index if not exists idx_src_grooming_appts_pet          on public.src_grooming_appointments (pet_code);
create index if not exists idx_src_grooming_appts_service      on public.src_grooming_appointments (service_code);


-- =====================================================================
-- ROW LEVEL SECURITY
-- Enabled on every src_ table. With no policies, only the secret key
-- (server-side scripts) can read or write. Customer and pet data is personal
-- information: define access and retention rules before opening any of it to
-- a client app (report 4.4 / 4.5.5).
-- =====================================================================
do $$
declare
  t text;
begin
  for t in
    select tablename from pg_tables
    where schemaname = 'public' and tablename like 'src\_%'
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end
$$;
