-- =====================================================================
-- PetHaven Group - database schema, phase 1: the four source systems
-- (Supabase / PostgreSQL). Safe to re-run (IF NOT EXISTS).
--
-- Apply with:  python scripts/apply_schema.py
--
-- SCOPE OF THIS FILE
--   Only what is needed to load the initial synthetic data for the four
--   source systems. Later layers of the agreed architecture (staging,
--   integration / MDM, data warehouse, governance) are NOT here yet; they are
--   added in later pull requests, once the synthetic data exists.
--
-- THE FOUR SOURCES (each is its own "system" with its own keys)
--   src_pos_*       SRC_POS       in-store point of sale
--   src_digital_*   SRC_DIGITAL   website and mobile app
--   src_product_*   SRC_PRODUCT   inventory / ERP (items and stock by location)
--   src_customer_*  SRC_CUSTOMER  customer and pet service system
--
-- RULES
--   * Each source keeps its OWN keys and its own copy of customers, products
--     and locations, on purpose: the systems share no identifiers (report
--     problems P1 and P3). Matching them is the job of the later MDM layer.
--   * Foreign keys exist only INSIDE one source, never between sources.
--     Cross-source references (e.g. a POS pickup naming a web order) are
--     plain text columns.
--   * Stock tables hold the current state only.
--   * Table prefixes in the public schema (not separate Postgres schemas) so
--     supabase-py reaches every table without extra API settings.
--   * Text CHECK constraints instead of enums; identity columns are
--     "BY DEFAULT" so the synthetic data generator can load its own IDs.
--
-- Removing tables from an older version of this schema (mdm_*, gov_*, v_*):
--   python scripts/apply_schema.py --reset      (development database only)
-- =====================================================================


-- =====================================================================
-- SRC_POS  -  in-store point of sale
-- Holds: sales and their lines, local stock, loyalty members, click and
-- collect pickups. Products are known here only by the POS product code.
-- =====================================================================
create table if not exists public.src_pos_stores (
  store_id    bigint generated by default as identity primary key,
  store_name  text not null unique,
  suburb      text,
  state       text
);

create table if not exists public.src_pos_loyalty_members (
  member_no           text primary key,
  first_name          text,
  last_name           text,
  email               text,
  phone               text,
  postcode            text,
  registered_store_id bigint references public.src_pos_stores (store_id),
  registered_at       timestamptz not null default now()
);

create table if not exists public.src_pos_sales (
  sale_id   bigint generated by default as identity primary key,
  store_id  bigint not null references public.src_pos_stores (store_id),
  member_no text references public.src_pos_loyalty_members (member_no),  -- null = walk-in
  sold_at   timestamptz not null
);

create table if not exists public.src_pos_sale_lines (
  sale_line_id        bigint generated by default as identity primary key,
  sale_id             bigint not null references public.src_pos_sales (sale_id) on delete cascade,
  product_code        text not null,          -- POS product code
  product_description text,
  quantity            integer not null check (quantity > 0),
  unit_price          numeric(10,2) not null check (unit_price >= 0)
);

create table if not exists public.src_pos_stock (
  store_id         bigint not null references public.src_pos_stores (store_id),
  product_code     text not null,
  quantity_on_hand integer not null check (quantity_on_hand >= 0),
  counted_at       timestamptz not null,
  primary key (store_id, product_code)
);

-- A click and collect order picked up in store. web_order_no names the order
-- in SRC_DIGITAL as plain text (no foreign key between systems).
create table if not exists public.src_pos_pickups (
  pickup_id     bigint generated by default as identity primary key,
  store_id      bigint not null references public.src_pos_stores (store_id),
  web_order_no  text not null,
  picked_up_at  timestamptz not null
);


-- =====================================================================
-- SRC_DIGITAL  -  website and mobile app
-- Holds: customer accounts, pet profiles, product catalogue, orders and
-- lines, and a stock snapshot refreshed overnight. Names locations as text.
-- =====================================================================
create table if not exists public.src_digital_customers (
  account_id  bigint generated by default as identity primary key,
  email       text not null unique,
  first_name  text,
  last_name   text,
  phone       text,
  created_at  timestamptz not null default now()
);

create table if not exists public.src_digital_pets (
  pet_id      bigint generated by default as identity primary key,
  account_id  bigint not null references public.src_digital_customers (account_id) on delete cascade,
  name        text not null,
  species     text not null check (species in ('dog','cat','bird','fish','small_animal','reptile','other')),
  breed       text,
  birth_date  date
);

create table if not exists public.src_digital_products (
  sku       text primary key,
  name      text not null,
  brand     text,
  category  text,
  price     numeric(10,2) not null check (price >= 0)
);

create table if not exists public.src_digital_orders (
  order_no         text primary key,
  account_id       bigint references public.src_digital_customers (account_id),  -- null = guest checkout
  ordered_at       timestamptz not null,
  status           text not null check (status in ('placed','fulfilled','cancelled')),
  delivery_method  text not null check (delivery_method in ('delivery','click_and_collect')),
  pickup_store     text                    -- store NAME, only for click and collect
);

create table if not exists public.src_digital_order_lines (
  order_line_id         bigint generated by default as identity primary key,
  order_no              text not null references public.src_digital_orders (order_no) on delete cascade,
  sku                   text not null references public.src_digital_products (sku),
  quantity              integer not null check (quantity > 0),
  unit_price            numeric(10,2) not null check (unit_price >= 0),
  fulfilment_location   text,              -- store name or distribution centre, as text
  line_status           text not null check (line_status in ('pending','shipped','collected','cancelled'))
);

create table if not exists public.src_digital_stock_snapshot (
  sku           text not null references public.src_digital_products (sku),
  location_name text not null,
  quantity      integer not null check (quantity >= 0),
  snapshot_at   timestamptz not null,
  primary key (sku, location_name)
);


-- =====================================================================
-- SRC_PRODUCT  -  inventory / ERP
-- Holds: items and stock by location (stores and the distribution centre).
-- Locations are identified by name only, with no location code.
-- Suppliers and purchase orders are out of scope for this phase.
-- =====================================================================
create table if not exists public.src_product_items (
  item_code   text primary key,
  item_name   text not null,
  brand       text,
  category    text,
  unit_cost   numeric(10,2) check (unit_cost >= 0),
  list_price  numeric(10,2) check (list_price >= 0)
);

create table if not exists public.src_product_stock (
  item_code         text not null references public.src_product_items (item_code),
  location_name     text not null,
  location_type     text not null check (location_type in ('store','dc')),
  quantity_on_hand  integer not null check (quantity_on_hand >= 0),
  updated_at        timestamptz not null,
  primary key (item_code, location_name)
);


-- =====================================================================
-- SRC_CUSTOMER  -  customer and pet service system
-- Holds: customers and their pets, with health and behaviour notes.
-- Grooming bookings are out of scope for this phase.
-- =====================================================================
create table if not exists public.src_customer_customers (
  customer_no  text primary key,
  first_name   text,
  last_name    text,
  email        text,
  phone        text,
  postcode     text,
  created_at   timestamptz not null default now()
);

create table if not exists public.src_customer_pets (
  pet_id           bigint generated by default as identity primary key,
  customer_no      text not null references public.src_customer_customers (customer_no) on delete cascade,
  name             text not null,
  species          text not null check (species in ('dog','cat','bird','fish','small_animal','reptile','other')),
  breed            text,
  birth_date       date,
  health_notes     text,
  behaviour_notes  text
);


-- =====================================================================
-- INDEXES on foreign-key columns (Postgres does not create these itself)
-- =====================================================================
create index if not exists idx_src_pos_loyalty_members_store on public.src_pos_loyalty_members (registered_store_id);
create index if not exists idx_src_pos_sales_store          on public.src_pos_sales (store_id);
create index if not exists idx_src_pos_sales_member         on public.src_pos_sales (member_no);
create index if not exists idx_src_pos_sale_lines_sale      on public.src_pos_sale_lines (sale_id);
create index if not exists idx_src_pos_sale_lines_product   on public.src_pos_sale_lines (product_code);
create index if not exists idx_src_pos_pickups_store        on public.src_pos_pickups (store_id);
create index if not exists idx_src_digital_pets_account     on public.src_digital_pets (account_id);
create index if not exists idx_src_digital_orders_account   on public.src_digital_orders (account_id);
create index if not exists idx_src_digital_lines_order      on public.src_digital_order_lines (order_no);
create index if not exists idx_src_digital_lines_sku        on public.src_digital_order_lines (sku);
create index if not exists idx_src_customer_pets_customer   on public.src_customer_pets (customer_no);


-- =====================================================================
-- ROW LEVEL SECURITY
-- Enabled on every src_ table. With no policies, only the secret key
-- (server-side scripts) can read or write. Customer and pet data is personal
-- information: define access and retention rules before opening any of it to
-- a client app (report 4.4 / 4.5.5).
-- =====================================================================
do $$
declare
  t text;
begin
  for t in
    select tablename from pg_tables
    where schemaname = 'public' and tablename like 'src\_%'
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end
$$;
